# Your presentation title
title: Um convite para você...

# Your presentation description (optional)
description: Acesse e descubra!

# Your name (optional)
author: Aline e Paulo

# The Reveal theme
reveal_theme: simple.css

# The Reveal transition
reveal_transition: slide

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 'controls: false, controlsLayout: "bottom-center"'

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme

